// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Token = require("./Token.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

function app(param) {
  return ReasonReact.element(undefined, undefined, Token.Token[/* make */1](/* array */[]));
}

exports.app = app;
/* Token Not a pure module */
